name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Compile Fortran (optional)
      run: |
        gfortran fortran/ultralight.f90 -o fortran/ultralight || echo "Fortran compilation skipped"

    - name: Precompute results (optional)
      run: |
        python backend/ultralight.py || echo "Precompute skipped"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend
        publish_branch: gh-pages
